### ISSUE TITLE
Global keyboard shortcuts for selecting colours

### ISSUE THREAD

**Issue by og2t** [Esshahn/spritemate#69]
In any context, pressing keys `0-9` and `a-f` would select the relevant colour.

**Comment by Esshahn** [comment]
Good idea. I still need to think about how to implement keyboard controls though, since most combinations fall in either one of the two categories:

* used by the browser ( like CMD + C )
* used by the user ( typing in stuff )

I don't want to override shortcuts that are of practical use, so I guess I have to check for typing vs. non-typing situations. Currently there's only the save dialog that uses player input, anyway.
